/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetNetworkAlertsSettings200ResponseMutingByPortSchedules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkAlertsSettings200ResponseMutingByPortSchedules{}

// GetNetworkAlertsSettings200ResponseMutingByPortSchedules Mute wireless unreachable alerts based on switch port schedules
type GetNetworkAlertsSettings200ResponseMutingByPortSchedules struct {
	// If true, then wireless unreachable alerts will be muted when caused by a port schedule
	Enabled *bool `json:"enabled,omitempty"`
}

// NewGetNetworkAlertsSettings200ResponseMutingByPortSchedules instantiates a new GetNetworkAlertsSettings200ResponseMutingByPortSchedules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkAlertsSettings200ResponseMutingByPortSchedules() *GetNetworkAlertsSettings200ResponseMutingByPortSchedules {
	this := GetNetworkAlertsSettings200ResponseMutingByPortSchedules{}
	return &this
}

// NewGetNetworkAlertsSettings200ResponseMutingByPortSchedulesWithDefaults instantiates a new GetNetworkAlertsSettings200ResponseMutingByPortSchedules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkAlertsSettings200ResponseMutingByPortSchedulesWithDefaults() *GetNetworkAlertsSettings200ResponseMutingByPortSchedules {
	this := GetNetworkAlertsSettings200ResponseMutingByPortSchedules{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseMutingByPortSchedules) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseMutingByPortSchedules) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseMutingByPortSchedules) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *GetNetworkAlertsSettings200ResponseMutingByPortSchedules) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o GetNetworkAlertsSettings200ResponseMutingByPortSchedules) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkAlertsSettings200ResponseMutingByPortSchedules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableGetNetworkAlertsSettings200ResponseMutingByPortSchedules struct {
	value *GetNetworkAlertsSettings200ResponseMutingByPortSchedules
	isSet bool
}

func (v NullableGetNetworkAlertsSettings200ResponseMutingByPortSchedules) Get() *GetNetworkAlertsSettings200ResponseMutingByPortSchedules {
	return v.value
}

func (v *NullableGetNetworkAlertsSettings200ResponseMutingByPortSchedules) Set(val *GetNetworkAlertsSettings200ResponseMutingByPortSchedules) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkAlertsSettings200ResponseMutingByPortSchedules) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkAlertsSettings200ResponseMutingByPortSchedules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkAlertsSettings200ResponseMutingByPortSchedules(val *GetNetworkAlertsSettings200ResponseMutingByPortSchedules) *NullableGetNetworkAlertsSettings200ResponseMutingByPortSchedules {
	return &NullableGetNetworkAlertsSettings200ResponseMutingByPortSchedules{value: val, isSet: true}
}

func (v NullableGetNetworkAlertsSettings200ResponseMutingByPortSchedules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkAlertsSettings200ResponseMutingByPortSchedules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


