/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue{}

// GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue An object mapping MAC addresses to IP addresses and client names
type GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue struct {
	// Assigned IP address
	Ip *string `json:"ip,omitempty"`
	// Client name
	Name *string `json:"name,omitempty"`
}

// NewGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue instantiates a new GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue() *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue {
	this := GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue{}
	return &this
}

// NewGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValueWithDefaults instantiates a new GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValueWithDefaults() *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue {
	this := GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) SetIp(v string) {
	o.Ip = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) SetName(v string) {
	o.Name = &v
}

func (o GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue struct {
	value *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue
	isSet bool
}

func (v NullableGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) Get() *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue {
	return v.value
}

func (v *NullableGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) Set(val *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue(val *GetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) *NullableGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue {
	return &NullableGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue{value: val, isSet: true}
}

func (v NullableGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkApplianceStaticRoutes200ResponseInnerFixedIpAssignmentsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


