/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetNetworkAlertsSettings200ResponseAlertsInnerFilters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkAlertsSettings200ResponseAlertsInnerFilters{}

// GetNetworkAlertsSettings200ResponseAlertsInnerFilters A hash of specific configuration data for the alert. Only filters specific to the alert will be updated.
type GetNetworkAlertsSettings200ResponseAlertsInnerFilters struct {
	// Conditions
	Conditions []GetNetworkAlertsSettings200ResponseAlertsInnerFiltersConditionsInner `json:"conditions,omitempty"`
	// Failure Type
	FailureType *string `json:"failureType,omitempty"`
	// Loopback Window (in sec)
	LookbackWindow *int32 `json:"lookbackWindow,omitempty"`
	// Min Duration
	MinDuration *int32 `json:"minDuration,omitempty"`
	// Name
	Name *string `json:"name,omitempty"`
	// Period
	Period *int32 `json:"period,omitempty"`
	// Priority
	Priority *string `json:"priority,omitempty"`
	// Regex
	Regex *string `json:"regex,omitempty"`
	// Selector
	Selector *string `json:"selector,omitempty"`
	// Serials
	Serials []string `json:"serials,omitempty"`
	// SSID Number
	SsidNum *int32 `json:"ssidNum,omitempty"`
	// Tag
	Tag *string `json:"tag,omitempty"`
	// Threshold
	Threshold *int32 `json:"threshold,omitempty"`
	// Timeout
	Timeout *int32 `json:"timeout,omitempty"`
}

// NewGetNetworkAlertsSettings200ResponseAlertsInnerFilters instantiates a new GetNetworkAlertsSettings200ResponseAlertsInnerFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkAlertsSettings200ResponseAlertsInnerFilters() *GetNetworkAlertsSettings200ResponseAlertsInnerFilters {
	this := GetNetworkAlertsSettings200ResponseAlertsInnerFilters{}
	return &this
}

// NewGetNetworkAlertsSettings200ResponseAlertsInnerFiltersWithDefaults instantiates a new GetNetworkAlertsSettings200ResponseAlertsInnerFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkAlertsSettings200ResponseAlertsInnerFiltersWithDefaults() *GetNetworkAlertsSettings200ResponseAlertsInnerFilters {
	this := GetNetworkAlertsSettings200ResponseAlertsInnerFilters{}
	return &this
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetConditions() []GetNetworkAlertsSettings200ResponseAlertsInnerFiltersConditionsInner {
	if o == nil || IsNil(o.Conditions) {
		var ret []GetNetworkAlertsSettings200ResponseAlertsInnerFiltersConditionsInner
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetConditionsOk() ([]GetNetworkAlertsSettings200ResponseAlertsInnerFiltersConditionsInner, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []GetNetworkAlertsSettings200ResponseAlertsInnerFiltersConditionsInner and assigns it to the Conditions field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetConditions(v []GetNetworkAlertsSettings200ResponseAlertsInnerFiltersConditionsInner) {
	o.Conditions = v
}

// GetFailureType returns the FailureType field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetFailureType() string {
	if o == nil || IsNil(o.FailureType) {
		var ret string
		return ret
	}
	return *o.FailureType
}

// GetFailureTypeOk returns a tuple with the FailureType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetFailureTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FailureType) {
		return nil, false
	}
	return o.FailureType, true
}

// HasFailureType returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasFailureType() bool {
	if o != nil && !IsNil(o.FailureType) {
		return true
	}

	return false
}

// SetFailureType gets a reference to the given string and assigns it to the FailureType field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetFailureType(v string) {
	o.FailureType = &v
}

// GetLookbackWindow returns the LookbackWindow field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetLookbackWindow() int32 {
	if o == nil || IsNil(o.LookbackWindow) {
		var ret int32
		return ret
	}
	return *o.LookbackWindow
}

// GetLookbackWindowOk returns a tuple with the LookbackWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetLookbackWindowOk() (*int32, bool) {
	if o == nil || IsNil(o.LookbackWindow) {
		return nil, false
	}
	return o.LookbackWindow, true
}

// HasLookbackWindow returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasLookbackWindow() bool {
	if o != nil && !IsNil(o.LookbackWindow) {
		return true
	}

	return false
}

// SetLookbackWindow gets a reference to the given int32 and assigns it to the LookbackWindow field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetLookbackWindow(v int32) {
	o.LookbackWindow = &v
}

// GetMinDuration returns the MinDuration field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetMinDuration() int32 {
	if o == nil || IsNil(o.MinDuration) {
		var ret int32
		return ret
	}
	return *o.MinDuration
}

// GetMinDurationOk returns a tuple with the MinDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetMinDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.MinDuration) {
		return nil, false
	}
	return o.MinDuration, true
}

// HasMinDuration returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasMinDuration() bool {
	if o != nil && !IsNil(o.MinDuration) {
		return true
	}

	return false
}

// SetMinDuration gets a reference to the given int32 and assigns it to the MinDuration field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetMinDuration(v int32) {
	o.MinDuration = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetName(v string) {
	o.Name = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetPeriod() int32 {
	if o == nil || IsNil(o.Period) {
		var ret int32
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetPeriodOk() (*int32, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given int32 and assigns it to the Period field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetPeriod(v int32) {
	o.Period = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetPriority(v string) {
	o.Priority = &v
}

// GetRegex returns the Regex field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetRegex() string {
	if o == nil || IsNil(o.Regex) {
		var ret string
		return ret
	}
	return *o.Regex
}

// GetRegexOk returns a tuple with the Regex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetRegexOk() (*string, bool) {
	if o == nil || IsNil(o.Regex) {
		return nil, false
	}
	return o.Regex, true
}

// HasRegex returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasRegex() bool {
	if o != nil && !IsNil(o.Regex) {
		return true
	}

	return false
}

// SetRegex gets a reference to the given string and assigns it to the Regex field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetRegex(v string) {
	o.Regex = &v
}

// GetSelector returns the Selector field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetSelector() string {
	if o == nil || IsNil(o.Selector) {
		var ret string
		return ret
	}
	return *o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetSelectorOk() (*string, bool) {
	if o == nil || IsNil(o.Selector) {
		return nil, false
	}
	return o.Selector, true
}

// HasSelector returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasSelector() bool {
	if o != nil && !IsNil(o.Selector) {
		return true
	}

	return false
}

// SetSelector gets a reference to the given string and assigns it to the Selector field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetSelector(v string) {
	o.Selector = &v
}

// GetSerials returns the Serials field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetSerials() []string {
	if o == nil || IsNil(o.Serials) {
		var ret []string
		return ret
	}
	return o.Serials
}

// GetSerialsOk returns a tuple with the Serials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetSerialsOk() ([]string, bool) {
	if o == nil || IsNil(o.Serials) {
		return nil, false
	}
	return o.Serials, true
}

// HasSerials returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasSerials() bool {
	if o != nil && !IsNil(o.Serials) {
		return true
	}

	return false
}

// SetSerials gets a reference to the given []string and assigns it to the Serials field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetSerials(v []string) {
	o.Serials = v
}

// GetSsidNum returns the SsidNum field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetSsidNum() int32 {
	if o == nil || IsNil(o.SsidNum) {
		var ret int32
		return ret
	}
	return *o.SsidNum
}

// GetSsidNumOk returns a tuple with the SsidNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetSsidNumOk() (*int32, bool) {
	if o == nil || IsNil(o.SsidNum) {
		return nil, false
	}
	return o.SsidNum, true
}

// HasSsidNum returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasSsidNum() bool {
	if o != nil && !IsNil(o.SsidNum) {
		return true
	}

	return false
}

// SetSsidNum gets a reference to the given int32 and assigns it to the SsidNum field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetSsidNum(v int32) {
	o.SsidNum = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetTag(v string) {
	o.Tag = &v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetThreshold() int32 {
	if o == nil || IsNil(o.Threshold) {
		var ret int32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given int32 and assigns it to the Threshold field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetThreshold(v int32) {
	o.Threshold = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) SetTimeout(v int32) {
	o.Timeout = &v
}

func (o GetNetworkAlertsSettings200ResponseAlertsInnerFilters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkAlertsSettings200ResponseAlertsInnerFilters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.FailureType) {
		toSerialize["failureType"] = o.FailureType
	}
	if !IsNil(o.LookbackWindow) {
		toSerialize["lookbackWindow"] = o.LookbackWindow
	}
	if !IsNil(o.MinDuration) {
		toSerialize["minDuration"] = o.MinDuration
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Regex) {
		toSerialize["regex"] = o.Regex
	}
	if !IsNil(o.Selector) {
		toSerialize["selector"] = o.Selector
	}
	if !IsNil(o.Serials) {
		toSerialize["serials"] = o.Serials
	}
	if !IsNil(o.SsidNum) {
		toSerialize["ssidNum"] = o.SsidNum
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	return toSerialize, nil
}

type NullableGetNetworkAlertsSettings200ResponseAlertsInnerFilters struct {
	value *GetNetworkAlertsSettings200ResponseAlertsInnerFilters
	isSet bool
}

func (v NullableGetNetworkAlertsSettings200ResponseAlertsInnerFilters) Get() *GetNetworkAlertsSettings200ResponseAlertsInnerFilters {
	return v.value
}

func (v *NullableGetNetworkAlertsSettings200ResponseAlertsInnerFilters) Set(val *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkAlertsSettings200ResponseAlertsInnerFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkAlertsSettings200ResponseAlertsInnerFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkAlertsSettings200ResponseAlertsInnerFilters(val *GetNetworkAlertsSettings200ResponseAlertsInnerFilters) *NullableGetNetworkAlertsSettings200ResponseAlertsInnerFilters {
	return &NullableGetNetworkAlertsSettings200ResponseAlertsInnerFilters{value: val, isSet: true}
}

func (v NullableGetNetworkAlertsSettings200ResponseAlertsInnerFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkAlertsSettings200ResponseAlertsInnerFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


