/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems{}

// GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems Items
type GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems struct {
	// Total number of items
	Total *int32 `json:"total,omitempty"`
	// Remaining number of items
	Remaining *int32 `json:"remaining,omitempty"`
}

// NewGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems instantiates a new GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems() *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems {
	this := GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems{}
	return &this
}

// NewGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItemsWithDefaults instantiates a new GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItemsWithDefaults() *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems {
	this := GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) SetTotal(v int32) {
	o.Total = &v
}

// GetRemaining returns the Remaining field value if set, zero value otherwise.
func (o *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) GetRemaining() int32 {
	if o == nil || IsNil(o.Remaining) {
		var ret int32
		return ret
	}
	return *o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) GetRemainingOk() (*int32, bool) {
	if o == nil || IsNil(o.Remaining) {
		return nil, false
	}
	return o.Remaining, true
}

// HasRemaining returns a boolean if a field has been set.
func (o *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) HasRemaining() bool {
	if o != nil && !IsNil(o.Remaining) {
		return true
	}

	return false
}

// SetRemaining gets a reference to the given int32 and assigns it to the Remaining field.
func (o *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) SetRemaining(v int32) {
	o.Remaining = &v
}

func (o GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Remaining) {
		toSerialize["remaining"] = o.Remaining
	}
	return toSerialize, nil
}

type NullableGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems struct {
	value *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems
	isSet bool
}

func (v NullableGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) Get() *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems {
	return v.value
}

func (v *NullableGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) Set(val *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems(val *GetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) *NullableGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems {
	return &NullableGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems{value: val, isSet: true}
}

func (v NullableGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationWirelessAirMarshalSettingsByNetwork200ResponseMetaCountsItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


