/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response{}

// GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response struct for GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response
type GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response struct {
	// VPN exclusion rules by network
	Items []UpdateNetworkApplianceTrafficShapingVpnExclusions200Response `json:"items,omitempty"`
}

// NewGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response instantiates a new GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response() *GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response {
	this := GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response{}
	return &this
}

// NewGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200ResponseWithDefaults instantiates a new GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200ResponseWithDefaults() *GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response {
	this := GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) GetItems() []UpdateNetworkApplianceTrafficShapingVpnExclusions200Response {
	if o == nil || IsNil(o.Items) {
		var ret []UpdateNetworkApplianceTrafficShapingVpnExclusions200Response
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) GetItemsOk() ([]UpdateNetworkApplianceTrafficShapingVpnExclusions200Response, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []UpdateNetworkApplianceTrafficShapingVpnExclusions200Response and assigns it to the Items field.
func (o *GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) SetItems(v []UpdateNetworkApplianceTrafficShapingVpnExclusions200Response) {
	o.Items = v
}

func (o GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response struct {
	value *GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response
	isSet bool
}

func (v NullableGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) Get() *GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response {
	return v.value
}

func (v *NullableGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) Set(val *GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response(val *GetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) *NullableGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response {
	return &NullableGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response{value: val, isSet: true}
}

func (v NullableGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationApplianceTrafficShapingVpnExclusionsByNetwork200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


