/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// checks if the GetOrganizationWirelessAirMarshalRules200ResponseItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationWirelessAirMarshalRules200ResponseItemsInner{}

// GetOrganizationWirelessAirMarshalRules200ResponseItemsInner struct for GetOrganizationWirelessAirMarshalRules200ResponseItemsInner
type GetOrganizationWirelessAirMarshalRules200ResponseItemsInner struct {
	Network *CreateNetworkWirelessAirMarshalRule201ResponseNetwork `json:"network,omitempty"`
	// Indicates whether or not clients are allowed to        connect to rogue SSIDs by default. (blocked by default)
	RuleId *string `json:"ruleId,omitempty"`
	// Indicates whether or not clients are allowed to        connect to rogue SSIDs by default. (blocked by default)
	Type *string `json:"type,omitempty"`
	// Updated at timestamp
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Created at timestamp
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Match *GetOrganizationWirelessAirMarshalRules200ResponseItemsInnerMatch `json:"match,omitempty"`
}

// NewGetOrganizationWirelessAirMarshalRules200ResponseItemsInner instantiates a new GetOrganizationWirelessAirMarshalRules200ResponseItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationWirelessAirMarshalRules200ResponseItemsInner() *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner {
	this := GetOrganizationWirelessAirMarshalRules200ResponseItemsInner{}
	return &this
}

// NewGetOrganizationWirelessAirMarshalRules200ResponseItemsInnerWithDefaults instantiates a new GetOrganizationWirelessAirMarshalRules200ResponseItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationWirelessAirMarshalRules200ResponseItemsInnerWithDefaults() *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner {
	this := GetOrganizationWirelessAirMarshalRules200ResponseItemsInner{}
	return &this
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetNetwork() CreateNetworkWirelessAirMarshalRule201ResponseNetwork {
	if o == nil || IsNil(o.Network) {
		var ret CreateNetworkWirelessAirMarshalRule201ResponseNetwork
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetNetworkOk() (*CreateNetworkWirelessAirMarshalRule201ResponseNetwork, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given CreateNetworkWirelessAirMarshalRule201ResponseNetwork and assigns it to the Network field.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) SetNetwork(v CreateNetworkWirelessAirMarshalRule201ResponseNetwork) {
	o.Network = &v
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetRuleId() string {
	if o == nil || IsNil(o.RuleId) {
		var ret string
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RuleId) {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) HasRuleId() bool {
	if o != nil && !IsNil(o.RuleId) {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given string and assigns it to the RuleId field.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) SetRuleId(v string) {
	o.RuleId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) SetType(v string) {
	o.Type = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetMatch returns the Match field value if set, zero value otherwise.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetMatch() GetOrganizationWirelessAirMarshalRules200ResponseItemsInnerMatch {
	if o == nil || IsNil(o.Match) {
		var ret GetOrganizationWirelessAirMarshalRules200ResponseItemsInnerMatch
		return ret
	}
	return *o.Match
}

// GetMatchOk returns a tuple with the Match field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) GetMatchOk() (*GetOrganizationWirelessAirMarshalRules200ResponseItemsInnerMatch, bool) {
	if o == nil || IsNil(o.Match) {
		return nil, false
	}
	return o.Match, true
}

// HasMatch returns a boolean if a field has been set.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) HasMatch() bool {
	if o != nil && !IsNil(o.Match) {
		return true
	}

	return false
}

// SetMatch gets a reference to the given GetOrganizationWirelessAirMarshalRules200ResponseItemsInnerMatch and assigns it to the Match field.
func (o *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) SetMatch(v GetOrganizationWirelessAirMarshalRules200ResponseItemsInnerMatch) {
	o.Match = &v
}

func (o GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.RuleId) {
		toSerialize["ruleId"] = o.RuleId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Match) {
		toSerialize["match"] = o.Match
	}
	return toSerialize, nil
}

type NullableGetOrganizationWirelessAirMarshalRules200ResponseItemsInner struct {
	value *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner
	isSet bool
}

func (v NullableGetOrganizationWirelessAirMarshalRules200ResponseItemsInner) Get() *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner {
	return v.value
}

func (v *NullableGetOrganizationWirelessAirMarshalRules200ResponseItemsInner) Set(val *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationWirelessAirMarshalRules200ResponseItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationWirelessAirMarshalRules200ResponseItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationWirelessAirMarshalRules200ResponseItemsInner(val *GetOrganizationWirelessAirMarshalRules200ResponseItemsInner) *NullableGetOrganizationWirelessAirMarshalRules200ResponseItemsInner {
	return &NullableGetOrganizationWirelessAirMarshalRules200ResponseItemsInner{value: val, isSet: true}
}

func (v NullableGetOrganizationWirelessAirMarshalRules200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationWirelessAirMarshalRules200ResponseItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


