/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UninstallNetworkSmDeviceAppsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UninstallNetworkSmDeviceAppsRequest{}

// UninstallNetworkSmDeviceAppsRequest struct for UninstallNetworkSmDeviceAppsRequest
type UninstallNetworkSmDeviceAppsRequest struct {
	// ids of applications to be uninstalled
	AppIds []string `json:"appIds"`
}

type _UninstallNetworkSmDeviceAppsRequest UninstallNetworkSmDeviceAppsRequest

// NewUninstallNetworkSmDeviceAppsRequest instantiates a new UninstallNetworkSmDeviceAppsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUninstallNetworkSmDeviceAppsRequest(appIds []string) *UninstallNetworkSmDeviceAppsRequest {
	this := UninstallNetworkSmDeviceAppsRequest{}
	this.AppIds = appIds
	return &this
}

// NewUninstallNetworkSmDeviceAppsRequestWithDefaults instantiates a new UninstallNetworkSmDeviceAppsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUninstallNetworkSmDeviceAppsRequestWithDefaults() *UninstallNetworkSmDeviceAppsRequest {
	this := UninstallNetworkSmDeviceAppsRequest{}
	return &this
}

// GetAppIds returns the AppIds field value
func (o *UninstallNetworkSmDeviceAppsRequest) GetAppIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AppIds
}

// GetAppIdsOk returns a tuple with the AppIds field value
// and a boolean to check if the value has been set.
func (o *UninstallNetworkSmDeviceAppsRequest) GetAppIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AppIds, true
}

// SetAppIds sets field value
func (o *UninstallNetworkSmDeviceAppsRequest) SetAppIds(v []string) {
	o.AppIds = v
}

func (o UninstallNetworkSmDeviceAppsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UninstallNetworkSmDeviceAppsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["appIds"] = o.AppIds
	return toSerialize, nil
}

func (o *UninstallNetworkSmDeviceAppsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"appIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUninstallNetworkSmDeviceAppsRequest := _UninstallNetworkSmDeviceAppsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUninstallNetworkSmDeviceAppsRequest)

	if err != nil {
		return err
	}

	*o = UninstallNetworkSmDeviceAppsRequest(varUninstallNetworkSmDeviceAppsRequest)

	return err
}

type NullableUninstallNetworkSmDeviceAppsRequest struct {
	value *UninstallNetworkSmDeviceAppsRequest
	isSet bool
}

func (v NullableUninstallNetworkSmDeviceAppsRequest) Get() *UninstallNetworkSmDeviceAppsRequest {
	return v.value
}

func (v *NullableUninstallNetworkSmDeviceAppsRequest) Set(val *UninstallNetworkSmDeviceAppsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUninstallNetworkSmDeviceAppsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUninstallNetworkSmDeviceAppsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUninstallNetworkSmDeviceAppsRequest(val *UninstallNetworkSmDeviceAppsRequest) *NullableUninstallNetworkSmDeviceAppsRequest {
	return &NullableUninstallNetworkSmDeviceAppsRequest{value: val, isSet: true}
}

func (v NullableUninstallNetworkSmDeviceAppsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUninstallNetworkSmDeviceAppsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


