/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner{}

// GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner struct for GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner
type GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner struct {
	// SKU of the required product
	Sku *string `json:"sku,omitempty"`
	// Number required
	Quantity *int32 `json:"quantity,omitempty"`
}

// NewGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner instantiates a new GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner() *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner {
	this := GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner{}
	return &this
}

// NewGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInnerWithDefaults instantiates a new GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInnerWithDefaults() *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner {
	this := GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner{}
	return &this
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) SetSku(v string) {
	o.Sku = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) SetQuantity(v int32) {
	o.Quantity = &v
}

func (o GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	return toSerialize, nil
}

type NullableGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner struct {
	value *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner
	isSet bool
}

func (v NullableGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) Get() *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner {
	return v.value
}

func (v *NullableGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) Set(val *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner(val *GetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) *NullableGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner {
	return &NullableGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner{value: val, isSet: true}
}

func (v NullableGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAdministeredLicensingSubscriptionSubscriptionsComplianceStatuses200ResponseInnerViolationsByProductClassInnerMissingEntitlementsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


