/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner{}

// GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner struct for GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner
type GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner struct {
	// asset id
	Id *string `json:"id,omitempty"`
	// asset name
	Name *string `json:"name,omitempty"`
}

// NewGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner instantiates a new GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner() *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner {
	this := GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner{}
	return &this
}

// NewGetOrganizationSplashThemes200ResponseInnerThemeAssetsInnerWithDefaults instantiates a new GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationSplashThemes200ResponseInnerThemeAssetsInnerWithDefaults() *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner {
	this := GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) SetName(v string) {
	o.Name = &v
}

func (o GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner struct {
	value *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner
	isSet bool
}

func (v NullableGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) Get() *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner {
	return v.value
}

func (v *NullableGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) Set(val *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner(val *GetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) *NullableGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner {
	return &NullableGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner{value: val, isSet: true}
}

func (v NullableGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationSplashThemes200ResponseInnerThemeAssetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


