/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner{}

// GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner struct for GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner
type GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner struct {
	// Type
	Type string `json:"type"`
	// Count
	Count int32 `json:"count"`
}

type _GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner

// NewGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner instantiates a new GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner(type_ string, count int32) *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner {
	this := GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner{}
	this.Type = type_
	this.Count = count
	return &this
}

// NewGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInnerWithDefaults instantiates a new GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInnerWithDefaults() *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner {
	this := GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner{}
	return &this
}

// GetType returns the Type field value
func (o *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) SetType(v string) {
	o.Type = v
}

// GetCount returns the Count field value
func (o *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) SetCount(v int32) {
	o.Count = v
}

func (o GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner := _GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner)

	if err != nil {
		return err
	}

	*o = GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner(varGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner)

	return err
}

type NullableGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner struct {
	value *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner
	isSet bool
}

func (v NullableGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) Get() *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner {
	return v.value
}

func (v *NullableGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) Set(val *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner(val *GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) *NullableGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner {
	return &NullableGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner{value: val, isSet: true}
}

func (v NullableGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationAssuranceAlertsOverviewByNetwork200ResponseItemsInnerSeverityCountsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


