/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetNetworkSmDeviceRestrictions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkSmDeviceRestrictions200Response{}

// GetNetworkSmDeviceRestrictions200Response struct for GetNetworkSmDeviceRestrictions200Response
type GetNetworkSmDeviceRestrictions200Response struct {
	// The list of restrictions for the device
	Restrictions []GetNetworkSmDeviceRestrictions200ResponseRestrictionsInner `json:"restrictions,omitempty"`
}

// NewGetNetworkSmDeviceRestrictions200Response instantiates a new GetNetworkSmDeviceRestrictions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkSmDeviceRestrictions200Response() *GetNetworkSmDeviceRestrictions200Response {
	this := GetNetworkSmDeviceRestrictions200Response{}
	return &this
}

// NewGetNetworkSmDeviceRestrictions200ResponseWithDefaults instantiates a new GetNetworkSmDeviceRestrictions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkSmDeviceRestrictions200ResponseWithDefaults() *GetNetworkSmDeviceRestrictions200Response {
	this := GetNetworkSmDeviceRestrictions200Response{}
	return &this
}

// GetRestrictions returns the Restrictions field value if set, zero value otherwise.
func (o *GetNetworkSmDeviceRestrictions200Response) GetRestrictions() []GetNetworkSmDeviceRestrictions200ResponseRestrictionsInner {
	if o == nil || IsNil(o.Restrictions) {
		var ret []GetNetworkSmDeviceRestrictions200ResponseRestrictionsInner
		return ret
	}
	return o.Restrictions
}

// GetRestrictionsOk returns a tuple with the Restrictions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSmDeviceRestrictions200Response) GetRestrictionsOk() ([]GetNetworkSmDeviceRestrictions200ResponseRestrictionsInner, bool) {
	if o == nil || IsNil(o.Restrictions) {
		return nil, false
	}
	return o.Restrictions, true
}

// HasRestrictions returns a boolean if a field has been set.
func (o *GetNetworkSmDeviceRestrictions200Response) HasRestrictions() bool {
	if o != nil && !IsNil(o.Restrictions) {
		return true
	}

	return false
}

// SetRestrictions gets a reference to the given []GetNetworkSmDeviceRestrictions200ResponseRestrictionsInner and assigns it to the Restrictions field.
func (o *GetNetworkSmDeviceRestrictions200Response) SetRestrictions(v []GetNetworkSmDeviceRestrictions200ResponseRestrictionsInner) {
	o.Restrictions = v
}

func (o GetNetworkSmDeviceRestrictions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkSmDeviceRestrictions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Restrictions) {
		toSerialize["restrictions"] = o.Restrictions
	}
	return toSerialize, nil
}

type NullableGetNetworkSmDeviceRestrictions200Response struct {
	value *GetNetworkSmDeviceRestrictions200Response
	isSet bool
}

func (v NullableGetNetworkSmDeviceRestrictions200Response) Get() *GetNetworkSmDeviceRestrictions200Response {
	return v.value
}

func (v *NullableGetNetworkSmDeviceRestrictions200Response) Set(val *GetNetworkSmDeviceRestrictions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkSmDeviceRestrictions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkSmDeviceRestrictions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkSmDeviceRestrictions200Response(val *GetNetworkSmDeviceRestrictions200Response) *NullableGetNetworkSmDeviceRestrictions200Response {
	return &NullableGetNetworkSmDeviceRestrictions200Response{value: val, isSet: true}
}

func (v NullableGetNetworkSmDeviceRestrictions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkSmDeviceRestrictions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


