/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner{}

// GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner struct for GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner
type GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner struct {
	// Name of the custom performance class
	Name *string `json:"name,omitempty"`
	// ID of the custom performance class
	CustomPerformanceClassId *string `json:"customPerformanceClassId,omitempty"`
	// Maximum latency in milliseconds
	MaxLatency *int32 `json:"maxLatency,omitempty"`
	// Maximum jitter in milliseconds
	MaxJitter *int32 `json:"maxJitter,omitempty"`
	// Maximum percentage of packet loss
	MaxLossPercentage *int32 `json:"maxLossPercentage,omitempty"`
}

// NewGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner instantiates a new GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner() *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner {
	this := GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner{}
	return &this
}

// NewGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInnerWithDefaults instantiates a new GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInnerWithDefaults() *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner {
	this := GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) SetName(v string) {
	o.Name = &v
}

// GetCustomPerformanceClassId returns the CustomPerformanceClassId field value if set, zero value otherwise.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) GetCustomPerformanceClassId() string {
	if o == nil || IsNil(o.CustomPerformanceClassId) {
		var ret string
		return ret
	}
	return *o.CustomPerformanceClassId
}

// GetCustomPerformanceClassIdOk returns a tuple with the CustomPerformanceClassId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) GetCustomPerformanceClassIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomPerformanceClassId) {
		return nil, false
	}
	return o.CustomPerformanceClassId, true
}

// HasCustomPerformanceClassId returns a boolean if a field has been set.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) HasCustomPerformanceClassId() bool {
	if o != nil && !IsNil(o.CustomPerformanceClassId) {
		return true
	}

	return false
}

// SetCustomPerformanceClassId gets a reference to the given string and assigns it to the CustomPerformanceClassId field.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) SetCustomPerformanceClassId(v string) {
	o.CustomPerformanceClassId = &v
}

// GetMaxLatency returns the MaxLatency field value if set, zero value otherwise.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) GetMaxLatency() int32 {
	if o == nil || IsNil(o.MaxLatency) {
		var ret int32
		return ret
	}
	return *o.MaxLatency
}

// GetMaxLatencyOk returns a tuple with the MaxLatency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) GetMaxLatencyOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxLatency) {
		return nil, false
	}
	return o.MaxLatency, true
}

// HasMaxLatency returns a boolean if a field has been set.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) HasMaxLatency() bool {
	if o != nil && !IsNil(o.MaxLatency) {
		return true
	}

	return false
}

// SetMaxLatency gets a reference to the given int32 and assigns it to the MaxLatency field.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) SetMaxLatency(v int32) {
	o.MaxLatency = &v
}

// GetMaxJitter returns the MaxJitter field value if set, zero value otherwise.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) GetMaxJitter() int32 {
	if o == nil || IsNil(o.MaxJitter) {
		var ret int32
		return ret
	}
	return *o.MaxJitter
}

// GetMaxJitterOk returns a tuple with the MaxJitter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) GetMaxJitterOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxJitter) {
		return nil, false
	}
	return o.MaxJitter, true
}

// HasMaxJitter returns a boolean if a field has been set.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) HasMaxJitter() bool {
	if o != nil && !IsNil(o.MaxJitter) {
		return true
	}

	return false
}

// SetMaxJitter gets a reference to the given int32 and assigns it to the MaxJitter field.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) SetMaxJitter(v int32) {
	o.MaxJitter = &v
}

// GetMaxLossPercentage returns the MaxLossPercentage field value if set, zero value otherwise.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) GetMaxLossPercentage() int32 {
	if o == nil || IsNil(o.MaxLossPercentage) {
		var ret int32
		return ret
	}
	return *o.MaxLossPercentage
}

// GetMaxLossPercentageOk returns a tuple with the MaxLossPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) GetMaxLossPercentageOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxLossPercentage) {
		return nil, false
	}
	return o.MaxLossPercentage, true
}

// HasMaxLossPercentage returns a boolean if a field has been set.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) HasMaxLossPercentage() bool {
	if o != nil && !IsNil(o.MaxLossPercentage) {
		return true
	}

	return false
}

// SetMaxLossPercentage gets a reference to the given int32 and assigns it to the MaxLossPercentage field.
func (o *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) SetMaxLossPercentage(v int32) {
	o.MaxLossPercentage = &v
}

func (o GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CustomPerformanceClassId) {
		toSerialize["customPerformanceClassId"] = o.CustomPerformanceClassId
	}
	if !IsNil(o.MaxLatency) {
		toSerialize["maxLatency"] = o.MaxLatency
	}
	if !IsNil(o.MaxJitter) {
		toSerialize["maxJitter"] = o.MaxJitter
	}
	if !IsNil(o.MaxLossPercentage) {
		toSerialize["maxLossPercentage"] = o.MaxLossPercentage
	}
	return toSerialize, nil
}

type NullableGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner struct {
	value *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner
	isSet bool
}

func (v NullableGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) Get() *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner {
	return v.value
}

func (v *NullableGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) Set(val *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner(val *GetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) *NullableGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner {
	return &NullableGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner{value: val, isSet: true}
}

func (v NullableGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkApplianceTrafficShapingCustomPerformanceClasses200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


