/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetNetworkMqttBrokers200ResponseInnerAuthentication type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkMqttBrokers200ResponseInnerAuthentication{}

// GetNetworkMqttBrokers200ResponseInnerAuthentication Authentication settings of the MQTT broker
type GetNetworkMqttBrokers200ResponseInnerAuthentication struct {
	// Username for the MQTT broker.
	Username *string `json:"username,omitempty"`
}

// NewGetNetworkMqttBrokers200ResponseInnerAuthentication instantiates a new GetNetworkMqttBrokers200ResponseInnerAuthentication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkMqttBrokers200ResponseInnerAuthentication() *GetNetworkMqttBrokers200ResponseInnerAuthentication {
	this := GetNetworkMqttBrokers200ResponseInnerAuthentication{}
	return &this
}

// NewGetNetworkMqttBrokers200ResponseInnerAuthenticationWithDefaults instantiates a new GetNetworkMqttBrokers200ResponseInnerAuthentication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkMqttBrokers200ResponseInnerAuthenticationWithDefaults() *GetNetworkMqttBrokers200ResponseInnerAuthentication {
	this := GetNetworkMqttBrokers200ResponseInnerAuthentication{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *GetNetworkMqttBrokers200ResponseInnerAuthentication) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkMqttBrokers200ResponseInnerAuthentication) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *GetNetworkMqttBrokers200ResponseInnerAuthentication) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *GetNetworkMqttBrokers200ResponseInnerAuthentication) SetUsername(v string) {
	o.Username = &v
}

func (o GetNetworkMqttBrokers200ResponseInnerAuthentication) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkMqttBrokers200ResponseInnerAuthentication) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableGetNetworkMqttBrokers200ResponseInnerAuthentication struct {
	value *GetNetworkMqttBrokers200ResponseInnerAuthentication
	isSet bool
}

func (v NullableGetNetworkMqttBrokers200ResponseInnerAuthentication) Get() *GetNetworkMqttBrokers200ResponseInnerAuthentication {
	return v.value
}

func (v *NullableGetNetworkMqttBrokers200ResponseInnerAuthentication) Set(val *GetNetworkMqttBrokers200ResponseInnerAuthentication) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkMqttBrokers200ResponseInnerAuthentication) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkMqttBrokers200ResponseInnerAuthentication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkMqttBrokers200ResponseInnerAuthentication(val *GetNetworkMqttBrokers200ResponseInnerAuthentication) *NullableGetNetworkMqttBrokers200ResponseInnerAuthentication {
	return &NullableGetNetworkMqttBrokers200ResponseInnerAuthentication{value: val, isSet: true}
}

func (v NullableGetNetworkMqttBrokers200ResponseInnerAuthentication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkMqttBrokers200ResponseInnerAuthentication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


