/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 July, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.48.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetOrganizationAssuranceAlertsOverviewByType200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationAssuranceAlertsOverviewByType200Response{}

// GetOrganizationAssuranceAlertsOverviewByType200Response struct for GetOrganizationAssuranceAlertsOverviewByType200Response
type GetOrganizationAssuranceAlertsOverviewByType200Response struct {
	// Organization Alert counts by type
	Items []GetOrganizationAssuranceAlertsOverviewByType200ResponseItemsInner `json:"items"`
	Meta GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseMeta `json:"meta"`
}

type _GetOrganizationAssuranceAlertsOverviewByType200Response GetOrganizationAssuranceAlertsOverviewByType200Response

// NewGetOrganizationAssuranceAlertsOverviewByType200Response instantiates a new GetOrganizationAssuranceAlertsOverviewByType200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationAssuranceAlertsOverviewByType200Response(items []GetOrganizationAssuranceAlertsOverviewByType200ResponseItemsInner, meta GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseMeta) *GetOrganizationAssuranceAlertsOverviewByType200Response {
	this := GetOrganizationAssuranceAlertsOverviewByType200Response{}
	this.Items = items
	this.Meta = meta
	return &this
}

// NewGetOrganizationAssuranceAlertsOverviewByType200ResponseWithDefaults instantiates a new GetOrganizationAssuranceAlertsOverviewByType200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationAssuranceAlertsOverviewByType200ResponseWithDefaults() *GetOrganizationAssuranceAlertsOverviewByType200Response {
	this := GetOrganizationAssuranceAlertsOverviewByType200Response{}
	return &this
}

// GetItems returns the Items field value
func (o *GetOrganizationAssuranceAlertsOverviewByType200Response) GetItems() []GetOrganizationAssuranceAlertsOverviewByType200ResponseItemsInner {
	if o == nil {
		var ret []GetOrganizationAssuranceAlertsOverviewByType200ResponseItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *GetOrganizationAssuranceAlertsOverviewByType200Response) GetItemsOk() ([]GetOrganizationAssuranceAlertsOverviewByType200ResponseItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *GetOrganizationAssuranceAlertsOverviewByType200Response) SetItems(v []GetOrganizationAssuranceAlertsOverviewByType200ResponseItemsInner) {
	o.Items = v
}

// GetMeta returns the Meta field value
func (o *GetOrganizationAssuranceAlertsOverviewByType200Response) GetMeta() GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseMeta {
	if o == nil {
		var ret GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *GetOrganizationAssuranceAlertsOverviewByType200Response) GetMetaOk() (*GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *GetOrganizationAssuranceAlertsOverviewByType200Response) SetMeta(v GetOrganizationAssuranceAlertsOverviewByNetwork200ResponseMeta) {
	o.Meta = v
}

func (o GetOrganizationAssuranceAlertsOverviewByType200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationAssuranceAlertsOverviewByType200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["meta"] = o.Meta
	return toSerialize, nil
}

func (o *GetOrganizationAssuranceAlertsOverviewByType200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetOrganizationAssuranceAlertsOverviewByType200Response := _GetOrganizationAssuranceAlertsOverviewByType200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetOrganizationAssuranceAlertsOverviewByType200Response)

	if err != nil {
		return err
	}

	*o = GetOrganizationAssuranceAlertsOverviewByType200Response(varGetOrganizationAssuranceAlertsOverviewByType200Response)

	return err
}

type NullableGetOrganizationAssuranceAlertsOverviewByType200Response struct {
	value *GetOrganizationAssuranceAlertsOverviewByType200Response
	isSet bool
}

func (v NullableGetOrganizationAssuranceAlertsOverviewByType200Response) Get() *GetOrganizationAssuranceAlertsOverviewByType200Response {
	return v.value
}

func (v *NullableGetOrganizationAssuranceAlertsOverviewByType200Response) Set(val *GetOrganizationAssuranceAlertsOverviewByType200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationAssuranceAlertsOverviewByType200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationAssuranceAlertsOverviewByType200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationAssuranceAlertsOverviewByType200Response(val *GetOrganizationAssuranceAlertsOverviewByType200Response) *NullableGetOrganizationAssuranceAlertsOverviewByType200Response {
	return &NullableGetOrganizationAssuranceAlertsOverviewByType200Response{value: val, isSet: true}
}

func (v NullableGetOrganizationAssuranceAlertsOverviewByType200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationAssuranceAlertsOverviewByType200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


